[path."/admin/realms:post:body"]
from_type = "String"
rust_type = "RealmRepresentation"
[path."/admin/realms:get:"]
from_type = "Value"
rust_type = "RealmRepresentation"
[path."/admin/realms/{realm}/users:get:"]
from_type = "Value"
rust_type = "TypeVec<UserRepresentation>"
[path."/admin/realms/{realm}/authentication/authenticator-providers:get:"]
from_type = "Value"
rust_type = "TypeVec<TypeMap<String, Value>>"
[path."/admin/realms/{realm}/authentication/client-authenticator-providers:get:"]
from_type = "Value"
rust_type = "TypeVec<TypeMap<String, Value>>"
[path."/admin/realms/{realm}/authentication/flows:get:"]
from_type = "Value"
rust_type = "AuthenticationFlowRepresentation"
[path."/admin/realms/{realm}/authentication/form-action-providers:get:"]
from_type = "Value"
rust_type = "TypeVec<TypeMap<String, Value>>"
[path."/admin/realms/{realm}/authentication/form-providers:get:"]
from_type = "Value"
rust_type = "TypeVec<TypeMap<String, Value>>"
[path."/admin/realms/{realm}/authentication/register-required-action:post:body"]
from_type = "TypeMap<String, String>"
rust_type = "RequiredActionProviderRepresentation"
[path."/admin/realms/{realm}/authentication/required-actions:get:"]
from_type = "Value"
rust_type = "TypeVec<RequiredActionProviderRepresentation>"
[path."/admin/realms/{realm}/authentication/unregistered-required-actions:get:"]
from_type = "Value"
rust_type = "TypeVec<RequiredActionProviderRepresentation>"
[path."/admin/realms/{realm}/clients-initial-access:get:"]
from_type = "Value"
rust_type = "TypeVec<ClientInitialAccessPresentation>"
[path."/admin/realms/{realm}/client-registration-policy/providers:get:"]
from_type = "Value"
rust_type = "TypeVec<TypeMap<String, Value>>"
[path."/admin/realms/{realm}/groups/{id}/role-mappings/clients/{client}:get:"]
from_type = "Value"
rust_type = "TypeVec<RoleRepresentation>"
[path."/admin/realms/{realm}/groups/{id}/role-mappings/clients/{client}/available:get:"]
from_type = "Value"
rust_type = "TypeVec<RoleRepresentation>"
[path."/admin/realms/{realm}/groups/{id}/role-mappings/clients/{client}/composite:get:"]
from_type = "Value"
rust_type = "TypeVec<RoleRepresentation>"
[path."/admin/realms/{realm}/users/{id}/role-mappings/clients/{client}:get:"]
from_type = "Value"
rust_type = "TypeVec<RoleRepresentation>"
[path."/admin/realms/{realm}/users/{id}/role-mappings/clients/{client}/available:get:"]
from_type = "Value"
rust_type = "TypeVec<RoleRepresentation>"
[path."/admin/realms/{realm}/users/{id}/role-mappings/clients/{client}/composite:get:"]
from_type = "Value"
rust_type = "TypeVec<RoleRepresentation>"
[path."/admin/realms/{realm}/client-scopes:get:"]
from_type = "Value"
rust_type = "TypeVec<ClientScopeRepresentation>"
[path."/admin/realms/{realm}/client-templates:get:"]
from_type = "Value"
rust_type = "TypeVec<ClientInitialAccessPresentation>"
[path."/admin/realms/{realm}/clients:get:"]
from_type = "Value"
rust_type = "TypeVec<ClientRepresentation>"
[path."/admin/realms/{realm}/clients/{id}/default-client-scopes:get:"]
from_type = "Value"
rust_type = "TypeVec<ClientScopeRepresentation>"
[path."/admin/realms/{realm}/clients/{id}/evaluate-scopes/protocol-mappers:get:"]
from_type = "Value"
rust_type = "TypeVec<ProtocolMapperRepresentation>"
[path."/admin/realms/{realm}/clients/{id}/evaluate-scopes/scope-mappings/{roleContainerId}/granted:get:"]
from_type = "Value"
rust_type = "TypeVec<RoleRepresentation>"
[path."/admin/realms/{realm}/clients/{id}/evaluate-scopes/scope-mappings/{roleContainerId}/not-granted:get:"]
from_type = "Value"
rust_type = "TypeVec<RoleRepresentation>"
[path."/admin/realms/{realm}/clients/{id}/offline-sessions:get:"]
from_type = "Value"
rust_type = "TypeVec<TypeMap<String, Value>>"
[path."/admin/realms/{realm}/clients/{id}/optional-client-scopes:get:"]
from_type = "Value"
rust_type = "TypeVec<ClientScopeRepresentation>"
[path."/admin/realms/{realm}/clients/{id}/user-sessions:get:"]
from_type = "Value"
rust_type = "TypeVec<TypeMap<String, Value>>"
[path."/admin/realms/{realm}/components:get:"]
from_type = "Value"
rust_type = "TypeVec<ComponentRepresentation>"
[path."/admin/realms/{realm}/components/{id}/sub-component-types:get:"]
from_type = "Value"
rust_type = "TypeVec<ComponentRepresentation>"
[path."/admin/realms/{realm}/groups:get:"]
from_type = "Value"
rust_type = "TypeVec<GroupRepresentation>"
[path."/admin/realms/{realm}/groups/{id}/members:get:"]
from_type = "Value"
rust_type = "TypeVec<UserRepresentation>"
# [path."/admin/realms/{realm}/identity-provider/instances:get:"]
# from_type = "Value"
# [path."/admin/realms/{realm}/identity-provider/instances/{alias}/mappers:get:"]
# from_type = "Value"
# [path."/admin/realms/{realm}/client-scopes/{id}/protocol-mappers/models:get:"]
# from_type = "Value"
# [path."/admin/realms/{realm}/client-scopes/{id}/protocol-mappers/protocol/{protocol}:get:"]
# from_type = "Value"
# [path."/admin/realms/{realm}/client-templates/{id}/protocol-mappers/models:get:"]
# from_type = "Value"
# [path."/admin/realms/{realm}/client-templates/{id}/protocol-mappers/protocol/{protocol}:get:"]
# from_type = "Value"
# [path."/admin/realms/{realm}/clients/{id}/protocol-mappers/models:get:"]
# from_type = "Value"
# [path."/admin/realms/{realm}/clients/{id}/protocol-mappers/protocol/{protocol}:get:"]
# from_type = "Value"
# [path."/admin/realms/{realm}/admin-events:get:"]
# from_type = "Value"
# [path."/admin/realms/{realm}/client-session-stats:get:"]
# from_type = "Value"
# [path."/admin/realms/{realm}/credential-registrators:get:"]
# from_type = "Value"
# [path."/admin/realms/{realm}/default-default-client-scopes:get:"]
# from_type = "Value"
# [path."/admin/realms/{realm}/default-groups:get:"]
# from_type = "Value"
# [path."/admin/realms/{realm}/default-optional-client-scopes:get:"]
# from_type = "Value"
# [path."/admin/realms/{realm}/events:get:"]
# from_type = "Value"
# [path."/admin/realms/{realm}/localization:get:"]
# from_type = "Value"
# [path."/admin/realms/{realm}/groups/{id}/role-mappings/realm:get:"]
# from_type = "Value"
# [path."/admin/realms/{realm}/groups/{id}/role-mappings/realm/available:get:"]
# from_type = "Value"
# [path."/admin/realms/{realm}/groups/{id}/role-mappings/realm/composite:get:"]
# from_type = "Value"
# [path."/admin/realms/{realm}/users/{id}/role-mappings/realm:get:"]
# from_type = "Value"
# [path."/admin/realms/{realm}/users/{id}/role-mappings/realm/available:get:"]
# from_type = "Value"
# [path."/admin/realms/{realm}/users/{id}/role-mappings/realm/composite:get:"]
# from_type = "Value"
# [path."/admin/realms/{realm}/clients/{id}/roles:get:"]
# from_type = "Value"
# [path."/admin/realms/{realm}/clients/{id}/roles/{role-name}/composites:get:"]
# from_type = "Value"
# [path."/admin/realms/{realm}/clients/{id}/roles/{role-name}/composites/clients/{clientUuid}:get:"]
# from_type = "Value"
# [path."/admin/realms/{realm}/clients/{id}/roles/{role-name}/composites/realm:get:"]
# from_type = "Value"
# [path."/admin/realms/{realm}/clients/{id}/roles/{role-name}/groups:get:"]
# from_type = "Value"
# [path."/admin/realms/{realm}/clients/{id}/roles/{role-name}/users:get:"]
# from_type = "Value"
# [path."/admin/realms/{realm}/roles:get:"]
# from_type = "Value"
# [path."/admin/realms/{realm}/roles/{role-name}/composites:get:"]
# from_type = "Value"
# [path."/admin/realms/{realm}/roles/{role-name}/composites/clients/{clientUuid}:get:"]
# from_type = "Value"
# [path."/admin/realms/{realm}/roles/{role-name}/composites/realm:get:"]
# from_type = "Value"
# [path."/admin/realms/{realm}/roles/{role-name}/groups:get:"]
# from_type = "Value"
# [path."/admin/realms/{realm}/roles/{role-name}/users:get:"]
# from_type = "Value"
# [path."/admin/realms/{realm}/roles-by-id/{role-id}/composites:get:"]
# from_type = "Value"
# [path."/admin/realms/{realm}/roles-by-id/{role-id}/composites/clients/{clientUuid}:get:"]
# from_type = "Value"
# [path."/admin/realms/{realm}/roles-by-id/{role-id}/composites/realm:get:"]
# from_type = "Value"
# [path."/admin/realms/{realm}/client-scopes/{id}/scope-mappings/clients/{client}:get:"]
# from_type = "Value"
# [path."/admin/realms/{realm}/client-scopes/{id}/scope-mappings/clients/{client}/available:get:"]
# from_type = "Value"
# [path."/admin/realms/{realm}/client-scopes/{id}/scope-mappings/clients/{client}/composite:get:"]
# from_type = "Value"
# [path."/admin/realms/{realm}/client-scopes/{id}/scope-mappings/realm:get:"]
# from_type = "Value"
# [path."/admin/realms/{realm}/client-scopes/{id}/scope-mappings/realm/available:get:"]
# from_type = "Value"
# [path."/admin/realms/{realm}/client-scopes/{id}/scope-mappings/realm/composite:get:"]
# from_type = "Value"
# [path."/admin/realms/{realm}/client-templates/{id}/scope-mappings/clients/{client}:get:"]
# from_type = "Value"
# [path."/admin/realms/{realm}/client-templates/{id}/scope-mappings/clients/{client}/available:get:"]
# from_type = "Value"
# [path."/admin/realms/{realm}/client-templates/{id}/scope-mappings/clients/{client}/composite:get:"]
# from_type = "Value"
# [path."/admin/realms/{realm}/client-templates/{id}/scope-mappings/realm:get:"]
# from_type = "Value"
# [path."/admin/realms/{realm}/client-templates/{id}/scope-mappings/realm/available:get:"]
# from_type = "Value"
# [path."/admin/realms/{realm}/client-templates/{id}/scope-mappings/realm/composite:get:"]
# from_type = "Value"
# [path."/admin/realms/{realm}/clients/{id}/scope-mappings/clients/{client}:get:"]
# from_type = "Value"
# [path."/admin/realms/{realm}/clients/{id}/scope-mappings/clients/{client}/available:get:"]
# from_type = "Value"
# [path."/admin/realms/{realm}/clients/{id}/scope-mappings/clients/{client}/composite:get:"]
# from_type = "Value"
# [path."/admin/realms/{realm}/clients/{id}/scope-mappings/realm:get:"]
# from_type = "Value"
# [path."/admin/realms/{realm}/clients/{id}/scope-mappings/realm/available:get:"]
# from_type = "Value"
# [path."/admin/realms/{realm}/clients/{id}/scope-mappings/realm/composite:get:"]
# from_type = "Value"
# [path."/admin/realms/{realm}/users/{id}/configured-user-storage-credential-types:get:"]
# from_type = "Value"
# [path."/admin/realms/{realm}/users/{id}/consents:get:"]
# from_type = "Value"
# [path."/admin/realms/{realm}/users/{id}/credentials:get:"]
# from_type = "Value"
# [path."/admin/realms/{realm}/users/{id}/federated-identity:get:"]
# from_type = "Value"
# [path."/admin/realms/{realm}/users/{id}/groups:get:"]
# from_type = "Value"
# [path."/admin/realms/{realm}/users/{id}/offline-sessions/{clientUuid}:get:"]
# from_type = "Value"
# [path."/admin/realms/{realm}/users/{id}/sessions:get:"]
# from_type = "Value"